import type { IMedia } from '.';
import type { TranslationFields } from './media.interface';
// tslint:disable:max-line-length
export interface IDocument extends IMedia {
  author?: string;
  secondAuthor?: string; // going to remove in favor of array for 'author' field
  authors?: string[]; // refactoring to be just array of strings (currently breaks Admin document search which is going away)
  yearWritten?: number;
  keywords?: string[];
  description?: string; // short description to show in list which could be written in by hand or auto-generated by cloud-function from beginning of document content body
  description_translations?: TranslationFields;
  location?: string;
  topic?: string;
  genre:
    | 'note'
    | 'topical'
    | 'word'
    | 'passage'
    | 'artifact'
    | 'site'
    | 'biography'
    | 'textual'
    | 'photo'
    | 'chart'
    | 'timeline';
  verse?: number; // used by notesService to extract current verse from appropriate verseId array item
  type: 'document';
  sections: IDocumentSection[];

  stringifiedSections?: string; // for Algolia indexed documents
}

export interface IDocumentSection {
  contentType: 'text' | 'image';
  text?: string;
  text_translations?: TranslationFields;
  imageId?: string;
}
